################### SERVER ##########################
spring.application.name=Grupo02
server.port=8090
server.servlet.context-path=/api
#http://localhost:8090/api


################### CONEXION BD (H2 - BASE DE DATOS EN MEMORIA) ##########################
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
#http://localhost:8090/api/h2-console

################### JPA - ##########################
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#para cargar data inicial data.sql
spring.jpa.defer-datasource-initialization=true

############### Los que tienen "##" Se elimina si lo utilizas el sql ###################
################### CONEXION BD (SQL - CURSO DE BASE DE DATOS ##########################
# Conexi�n a tu instancia local SQLEXPRESS
## spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pf01_db;encrypt=false;trustServerCertificate=true;
# Tu usuario 'sa' que habilitamos
## spring.datasource.username=sa
# Tu contrase�a que configuramos
## spring.datasource.password=123456
## spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

################### JPA (CONFIGURACI�N PARA CREAR TABLAS DEL CURSO DE BASE DE DATOS) ##########################
# 1. Le decimos que hable "idioma" SQL Server
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
## spring.jpa.properties.hibernate.format_sql=true

# 2. ESTA ES LA MAGIA: 'update' crea las tablas si no existen, y si existen, las actualiza.
## spring.jpa.hibernate.ddl-auto=update

# 3. Muestra el SQL en la consola para que veas cuando crea las tablas
## spring.jpa.show-sql=true
# SWAGGER
#http://localhost:8090/api/swagger-ui/

